// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFw8DESYbb4bHL7dPlftt_9e3_hYSmW8',
    appId: '1:967166529615:web:ef4cbd9946d45ed2d69a3a',
    messagingSenderId: '967166529615',
    projectId: 'cerebro-plus-mobile',
    authDomain: 'cerebro-plus-mobile.firebaseapp.com',
    databaseURL: 'https://cerebro-plus-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cerebro-plus-mobile.appspot.com',
    measurementId: 'G-M305PFE4FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrFvKXmInHUrQcda1EFuZDVVzpzO0gxGw',
    appId: '1:967166529615:android:4eabc8b81503c110d69a3a',
    messagingSenderId: '967166529615',
    projectId: 'cerebro-plus-mobile',
    databaseURL: 'https://cerebro-plus-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cerebro-plus-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTMPWLMZFIk1WVKFpfsFuKNgjHz8U7rNM',
    appId: '1:967166529615:ios:8d7e08c02e5e8a03d69a3a',
    messagingSenderId: '967166529615',
    projectId: 'cerebro-plus-mobile',
    databaseURL: 'https://cerebro-plus-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cerebro-plus-mobile.appspot.com',
    iosBundleId: 'com.example.cerebroMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTMPWLMZFIk1WVKFpfsFuKNgjHz8U7rNM',
    appId: '1:967166529615:ios:5ac9c3f0ba0f7b6cd69a3a',
    messagingSenderId: '967166529615',
    projectId: 'cerebro-plus-mobile',
    databaseURL: 'https://cerebro-plus-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cerebro-plus-mobile.appspot.com',
    iosBundleId: 'com.example.cerebroMobile.RunnerTests',
  );
}
